name: Build and Deploy

on:
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ArturLukianov/arturlukianov.github.io  # Replace with your Pages repo
          publish_branch: main                       # Branch used by GitHub Pages
          publish_dir: ./dist                        # Your build output directory
          personal_token: ${{ secrets.PAGES_TOKEN }}          # PAT with repo permissions
          destination_dir: soc-shuriken
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
